config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'team' 		=> 'static_pages#team'
  get 'portfolio' 	=> 'static_pages#portfolio'
  get 'admin' 		=> 'static_pages#admin'
  get 'join' 		=> 'team_applications#new'
  post 'join' 		=> 'team_applications#create'
  get 'request'		=> 'proposals#new'
  post 'request' 	=> 'proposals#create'
  get 'contact' 	=> 'messages#new'
  post 'contact' 	=> 'messages#create'

  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :proposals, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show, :destroy]
  resources :team_applications, only: [:index, :show, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :restrict_to_logged_in, only: [:admin]

  def home
    render layout: 'home'
  end

  def team
  end

  def portfolio
  end

  def admin
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<% provide(:title, "Admin") %>

<p><%= link_to "Messages", messages_path %></p>
<p><%= link_to "Proposals", proposals_path %></p>
<p><%= link_to "Applications", team_applications_path %></p><br>
<p><%= link_to "Users", users_path %> </p>

app/views/static_pages/portfolio.html.erb
<% provide(:title, "Portfolio") %>

<h1> <%= yield(:title) %> </h1>

app/views/static_pages/team.html.erb
<% provide(:title, "Team") %>

<h1> <%= yield(:title) %> </h1>