config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'team' 		=> 'static_pages#team'
  get 'portfolio' 	=> 'static_pages#portfolio'
  get 'admin' 		=> 'static_pages#admin'
  get 'join' 		=> 'team_applications#new'
  post 'join' 		=> 'team_applications#create'
  get 'request'		=> 'proposals#new'
  post 'request' 	=> 'proposals#create'
  get 'contact' 	=> 'messages#new'
  post 'contact' 	=> 'messages#create'

  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :proposals, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show, :destroy]
  resources :team_applications, only: [:index, :show, :destroy]

end

app/models/team_application.rb
class TeamApplication < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,  format: {with: VALID_EMAIL_REGEX}
  validates :date_of_birth, presence: true
  validates :resume, presence: true

  mount_uploader :resume, FileSubmissionUploader

  default_scope -> { order(created_at: :desc) }

end

app/controllers/team_applications_controller.rb
class TeamApplicationsController < ApplicationController

  before_action :restrict_to_logged_in, only: [:index, :show, :destroy]

  def index
    @team_applications = TeamApplication.paginate(page: params[:page])
  end

  def new
    @application = TeamApplication.new
  end

  def create
    @application = TeamApplication.new(application_params)
    if @application.save
      NotificationMailer.application(@application).deliver_now
      flash.now[:success] = "Application submitted"
    end
    render 'new'
  end

  def show
    @application = TeamApplication.find(params[:id])
  end

  def destroy
    TeamApplication.find(params[:id]).destroy
    flash[:success] = "Application deleted"
    redirect_to team_applications_path
  end


  private
    
    def application_params
      params.require(:team_application).permit(:first_name, :last_name, :email, :date_of_birth, :attends_unc, :github_url, :linkedin_url, :website_url, :resume, :cover_letter)
    end
end

app/helpers/team_applications_helper.rb
module TeamApplicationsHelper
end

app/views/team_applications/_team_application.html.erb
    <p><%=a.first_name%> <%= a.last_name %> </p>
    <p> <%= a.email %></p>
    <p> DOB: <%= a.date_of_birth.to_formatted_s(:long_ordinal)%></p>

    <p> Attends UNC: <%= a.attends_unc ? "Yes" : "No" %></p>

    <p> Github: <%= link_to a.github_url unless a.github_url.nil?%></p>
    <p> LinkedIn: <%= link_to a.linkedin_url unless a.linkedin_url.nil?%></p>
    <p> Website: <%= link_to a.website_url unless a.website_url.nil?%></p>

    <p> <%= link_to "View resume", a.resume_url %></p>

    <p>Cover Letter: <br><%= a.cover_letter unless a.cover_letter.nil? %></p>

    <p> Submitted on: <%= a.created_at.to_formatted_s(:long_ordinal) %> </p>

app/views/team_applications/create.html.erb
<h1>TeamApplications#create</h1>
<p>Find me in app/views/team_applications/create.html.erb</p>

app/views/team_applications/index.html.erb
<h1>TeamApplications#index</h1>
<p>Find me in app/views/team_applications/index.html.erb</p>

<%= will_paginate %>

<% @team_applications.each do |a| %>

  <div class="well">
    <%= render 'team_application', a: a%>
    <%= link_to "Permalink", team_application_path(a), class: "btn btn-primary"    %>
    <%= link_to 'Delete', a, method: :delete, class: "btn btn-danger",  data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<%= will_paginate %>

app/views/team_applications/new.html.erb
<%= provide(:title, "Join")%>
<h1>Join Our Team</h1>

<p>Find me in app/views/team_applications/new.html.erb</p>

<div class="row">

    <%= form_for(@application, url: join_path) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :date_of_birth %>
      <%= f.date_field :date_of_birth, class: 'form-control' %>

      <%= f.label "Current UNC student?" %>
      <%= f.check_box :attends_unc, class: 'form-control' %>

      <%= f.label "GitHub URL" %>
      <%= f.url_field :github_url, class: 'form-control', placeholder: 'Optional' %>

      <%= f.label "LinkedIn URL" %>
      <%= f.url_field :linkedin_url, class: 'form-control', placeholder: 'Optional' %>
      
      <%= f.label "Personal website URL" %>
      <%= f.url_field :website_url, class: 'form-control', placeholder: 'Optional' %>

      <%= f.label "Resume (pdf, doc, docx)" %>
      <%= f.file_field :resume, class: 'form-control', accept: '.doc, .docx, .pdf'  %>

      <%= f.label :cover_letter %>
      <%= f.text_area :cover_letter, class: 'form-control', rows: '10' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %> 

</div>

app/views/team_applications/show.html.erb
<h1>TeamApplications#show</h1>
<p>Find me in app/views/team_applications/show.html.erb</p>

<%= render 'team_application', a: @application %>