config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'team' 		=> 'static_pages#team'
  get 'portfolio' 	=> 'static_pages#portfolio'
  get 'admin' 		=> 'static_pages#admin'
  get 'join' 		=> 'team_applications#new'
  post 'join' 		=> 'team_applications#create'
  get 'request'		=> 'proposals#new'
  post 'request' 	=> 'proposals#create'
  get 'contact' 	=> 'messages#new'
  post 'contact' 	=> 'messages#create'

  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :proposals, only: [:index, :show, :destroy]
  resources :messages, only: [:index, :show, :destroy]
  resources :team_applications, only: [:index, :show, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul >
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "Team",   team_path %></li>
      <li><%= link_to "Portfolio",   portfolio_path %></li>
      <li><%= link_to "Request",   request_path %></li>
      <li><%= link_to "Join",   join_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  <div class="copyright">
        Copyright © 2015 Guru Solutions, Inc. All rights reserved.
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
       <%= link_to "GURU DEV", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="header">
      <ul class="nav navbar-nav navbar-right">
          <li class="active"><%= link_to "Team", team_path%></li>
          <li><%= link_to "Portfolio", portfolio_path %></li>
          <li><%= link_to "Request", request_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <% if logged_in? %>
             <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Submissions</a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Applications", team_applications_path %></li>
                  <li><%= link_to "Proposals", proposals_path %></li>
                  <li><%= link_to "Messages", messages_path %></li>
                  <li> <%= link_to "Log out", logout_path, method: "delete" %> </li> 
                </ul>
             </li>
          <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>

    <% yield :stylesheets %>
    <% unless current_page?(controller: 'static_pages', action: 'home') %>
      <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %> 
    <% end %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
  	<%= render 'layouts/header'%>
    <div class="container"> 
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div> 
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <%= stylesheet_link_tag 'homepage', media: 'all', 'data-turbolinks-track' => true %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
      <%= render 'layouts/header'%>

      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

    <section class="cover">
        <div class="container-fullwidth" id="overlay">
            <div class="overlay-text container">
                <h1>About Us</h1>
                <p>
                We are a team of software developers based out of the University of North Carolina at Chapel Hill.  Being at a liberal arts school, our founders, Morgan Howell and Joshua Potter, recognized the need for technological support and assistance for other campus departments and clubs as well as local start-ups.  Guru Solutions was created to meet this need.  We are a hardworking group of individuals eager to utilize our knowledge to catalyze ideas in our community as well as accelerate our own ideas throughout campus.
                </p>
            </div>
        </div>
    </section>
    
    <section class="qualities container-fullwidth">
            <div class="row">
                <h1>Why We're Cool</h1>
                <div class="col-md-4" id="better">
                    <img src="assets/icons/bars.png" />
                    <h3>Better</h3>
                    <p>We love what we do. We are eager to tackle problems and come up with creative and innovative solutions. We may be young, but years of experience can't make up for the enthusiam, creative energy and dedication we will put toward any project set in front of us.</p>
                </div>
                <div class="col-md-4"  id="different">
                    <img src="assets/icons/beaker.png" />
                    <h3>Different</h3>
                    <p>As students, we are actively involved with many different aspects of computer science. By having teammates who are well rounded instead of specializing in different areas, we are able to take a more holistic approach to problems. We thoroughly consider all solutions and select the one that is the best fit for the company.</p>
                </div>
                <div class="col-md-4" id="creative">
                    <img src="assets/icons/globe.png" />
                    <h3>Creative</h3>
                    <p>Though we all major in computer science, we also all have at least one other major or minor in a different field. This adds diversity to our thought processees, helping us to develope unique and effective solutions to any problems.</p>
                </div>
            </div>
    </section>
    
    <section class="works container-fullwidth">
    	<h1>Our Works</h1>
    	<div class="container">
        	<a href="#"><div class="col-md-4"> 
                	<img src="assets/works/crave.png"/>
                	<h3> Coming Soon! </h3>
                </div></a>

                <a href="#"><div class="col-md-4">
                         <img src="assets/works/pay.png"/>
                        <h3> Coming Soon!</h3>                    
		</div></a>

                <a href="#"><div class="col-md-4">
                         <img src="assets/works/cyanoid.png"/>
                         <h3>Coming Soon!</h3>
                </div></a>
	</div>
    </section>
    
    <section class="team container-fullwidth">
	<div class="container">
            <h1>Our Team</h1>
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/morgan.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Morgan Howell</div>
                    <div class="member-job">I'm a double major in computer science and business. I would like the think of myself as an aspiring entrepreneur with a knack for collaborative software development teams.</div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/joshua.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Joshua Potter</div>
                    <div class="member-job">I'm a senior majoring in Computer Science and Mathamatics. I have six years of development experience, ranging from research positions to jobs to personal projects.</div>
                </div>          
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/bimba.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Bimba Shrestha</div>
                    <div class="member-job">I'm a freshman majoring in computer science and mathamatical decision sciences. I enjoy technology and medicine and conduct reseach in medical image analysis and bioinformatics</div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/kammy.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Kammy Liu</div>
                    <div class="member-job">I'm a junior majoring in computer science and psycology. My favorite thing about computer science is the ability to improve people's lives from a desk and a laptop</div>
                </div>                    
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/lucas.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Lucas Fang</div>
                    <div class="member-job">I'm a senior majoring in computer science and minoring in business and music. I focus on mobile and full-stack development and also play piano in my free time.</div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/laura.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Laura Gill</div>
                    <div class="member-job">I'm a junior computer science major and business minor. I love that through developing for people in different fields, I am able to learn about all different types of careers </div>
                </div>  
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="member-img">
                        <a href="#">
                            <img src="assets/members/draisin.jpg"/>
                        </a>
                    </div>
                    <div class="member-name">Aaron Mays</div>
                    <div class="member-job">waiting on content</div>
                </div>
             </div>
	</div>
    </section>

    
    <section class="contact container-fullwidth">
            <div class="contact-us container">
                <h1>Let's Get in Touch!</h1>
                <p> Are you an awesome developer looking to take on some new exciting projects with a team of super cool people? Do you have a startup you need awesome developers to help make a success? Do you have any other questions for us, or maybe just want to say "Hi"? Let us know! </p>
                <button class="contact-btn" >Contact Us</button>
            </div>
    </section>
     
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>